//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-post_api-SSD_SERVICE_ID_sd_jrB1b5Y2YUWX5gEi
import { post_api as SSD_SERVICE_ID_sd_jrB1b5Y2YUWX5gEi } from './sd-services/Post/post_api';
//CORE_REFERENCE_IMPORT-login-SSD_SERVICE_ID_sd_2NWhw0N4zVsBdyXO
import { login as SSD_SERVICE_ID_sd_2NWhw0N4zVsBdyXO } from './sd-services/login/login';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-post_api-SSD_SERVICE_ID_sd_jrB1b5Y2YUWX5gEi
SSD_SERVICE_ID_sd_jrB1b5Y2YUWX5gEi,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-login-SSD_SERVICE_ID_sd_2NWhw0N4zVsBdyXO
SSD_SERVICE_ID_sd_2NWhw0N4zVsBdyXO,
];
